logging:
  level:
    org.springframework: WARN
    fr.cailliaud: INFO
    org.hibernate.SQL: DEBUG

batch:
  file: file:./data/heroes.xml

spring:

  datasource-business:
    jdbcUrl: jdbc:h2:file:e:/DATABASE/business
    driverClassName: org.h2.Driver
    username: alex
    password: password
    platform: business
    initialization-mode: always


  datasource-batch:
    jdbcUrl: jdbc:h2:file:e:/DATABASE/technicalDb
    driverClassName: org.h2.Driver
    username: toto
    password: toto
    platform: batch


